# Generated by Django 3.1.3 on 2020-11-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clienttext',
            name='keywords',
            field=models.ManyToManyField(to='myapi.Keyword'),
        ),
    ]
