# Generated by Django 3.1.3 on 2020-11-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20201128_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttext',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='myapi.clienttext'),
        ),
    ]
