# Generated by Django 3.1.3 on 2020-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201128_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttext',
            name='keyw',
            field=models.JSONField(default='********'),
        ),
    ]
