# Generated by Django 3.1.3 on 2020-11-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_clienttext_keyw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttext',
            name='keyw',
        ),
    ]
